name = "cymanage"
compatibility_date = "2026-08-11"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "cymanage"
database_id = "c5709ee2-0b3a-4803-87d7-1da94cc3025c"
preview_database_id = "c5709ee2-0b3a-4803-87d7-1da94cc3025c"
